# Generated by Django 5.1.3 on 2024-11-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='tickets',
        ),
    ]
